name: Build app and deploy to aliyun
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '20'
      - name: Install npm dependencies
        run: npm install
      - name: Run build task
        run: npm run build
      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@v2.1.5
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
          ARGS: '-rltgoDzvO --delete'
          SOURCE: './.output'
          REMOTE_HOST: '47.116.126.150'
          REMOTE_USER: root
          TARGET: /www/blog/blog-nuxt
      - name: SSH into server and restart PM2
        uses: appleboy/ssh-action@master
        with:
          host: '47.116.126.150'
          username: root
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /www/blog/blog-nuxt
            pm2 restart all
